export interface Theme {
  name: string;
  colors: Record<string, string>;
  typography: Record<string, string>;
  radius: Record<string, string>;
  fonts: {
    heading: string;
    body: string;
    mono: string;
  };
}

export const themes: Theme[] = [
  {
    name: "Mintlify",
    fonts: {
      heading: "Inter",
      body: "Inter",
      mono: "Geist Mono",
    },
    typography: {
      "heading-weight": "600",
      "heading-tracking": "-0.02em",
      "heading-leading": "1.15",
      "body-leading": "1.5",
    },
    radius: {
      sm: "8px",
      md: "16px",
      lg: "24px",
    },
    colors: {
      brand: "#18E299",
      "brand-hover": "#0fa76e",
      "brand-active": "#0d8f5e",
      "brand-foreground": "#0d0d0d",
      surface: "#ffffff",
      "surface-raised": "#fafafa",
      "surface-overlay": "#f5f5f5",
      border: "#e5e5e5",
      primary: "#0d0d0d",
      secondary: "#333333",
      muted: "#888888",
      error: "#f87171",
      success: "#4ade80",
      gold: "#FFD700",
      "gold-light": "#b8960b",
      silver: "#777777",
      bronze: "#8b5e20",
    },
  },
  {
    name: "Composio",
    fonts: {
      heading: "Space Grotesk",
      body: "Space Grotesk",
      mono: "JetBrains Mono",
    },
    typography: {
      "heading-weight": "400",
      "heading-tracking": "0",
      "heading-leading": "0.87",
      "body-leading": "1.5",
    },
    radius: {
      sm: "2px",
      md: "4px",
      lg: "4px",
    },
    colors: {
      brand: "#0007cd",
      "brand-hover": "#0009ff",
      "brand-active": "#0006a8",
      "brand-foreground": "#ffffff",
      surface: "#0f0f0f",
      "surface-raised": "#000000",
      "surface-overlay": "#1a1a1a",
      border: "#1f1f1f",
      primary: "#ffffff",
      secondary: "#999999",
      muted: "#444444",
      error: "#f87171",
      success: "#4ade80",
      gold: "#FFD700",
      "gold-light": "#FFED80",
      silver: "#C0C0C0",
      bronze: "#CD7F32",
    },
  },
  {
    name: "Kraken",
    fonts: {
      heading: "IBM Plex Sans",
      body: "IBM Plex Sans",
      mono: "IBM Plex Mono",
    },
    typography: {
      "heading-weight": "700",
      "heading-tracking": "-0.02em",
      "heading-leading": "1.17",
      "body-leading": "1.38",
    },
    radius: {
      sm: "6px",
      md: "12px",
      lg: "16px",
    },
    colors: {
      brand: "#7132f5",
      "brand-hover": "#5741d8",
      "brand-active": "#5b1ecf",
      "brand-foreground": "#ffffff",
      surface: "#101114",
      "surface-raised": "#1a1b21",
      "surface-overlay": "#22232b",
      border: "#292d3a",
      primary: "#ffffff",
      secondary: "#9497a9",
      muted: "#686b82",
      error: "#f87171",
      success: "#4ade80",
      gold: "#FFD700",
      "gold-light": "#FFED80",
      silver: "#C0C0C0",
      bronze: "#CD7F32",
    },
  },
  {
    name: "Superhuman",
    fonts: {
      heading: "DM Sans",
      body: "DM Sans",
      mono: "Geist Mono",
    },
    typography: {
      "heading-weight": "500",
      "heading-tracking": "-0.02em",
      "heading-leading": "0.96",
      "body-leading": "1.5",
    },
    radius: {
      sm: "8px",
      md: "8px",
      lg: "16px",
    },
    colors: {
      brand: "#1b1938",
      "brand-hover": "#2a2550",
      "brand-active": "#141230",
      "brand-foreground": "#ffffff",
      surface: "#ffffff",
      "surface-raised": "#fafafa",
      "surface-overlay": "#f5f5f5",
      border: "#dcd7d3",
      primary: "#292827",
      secondary: "#666666",
      muted: "#999999",
      error: "#f87171",
      success: "#4ade80",
      gold: "#FFD700",
      "gold-light": "#b8960b",
      silver: "#777777",
      bronze: "#8b5e20",
    },
  },
  {
    name: "Stripe",
    fonts: { heading: "Inter", body: "Inter", mono: "Source Code Pro" },
    typography: { "heading-weight": "300", "heading-tracking": "-0.03em", "heading-leading": "1.05", "body-leading": "1.40" },
    radius: { sm: "4px", md: "6px", lg: "8px" },
    colors: {
      brand: "#533afd", "brand-hover": "#4434d4", "brand-active": "#2e2b8c", "brand-foreground": "#ffffff",
      surface: "#ffffff", "surface-raised": "#f6f5f4", "surface-overlay": "#ffffff",
      border: "#e5edf5", primary: "#0a2540", secondary: "#4d5b6e", muted: "#8898a8",
      error: "#ea2261", success: "#15be53",
      gold: "#FFD700", "gold-light": "#b8960b", silver: "#777777", bronze: "#8b5e20",
    },
  },
  {
    name: "Linear",
    fonts: { heading: "Inter", body: "Inter", mono: "IBM Plex Mono" },
    typography: { "heading-weight": "500", "heading-tracking": "-0.03em", "heading-leading": "1.00", "body-leading": "1.50" },
    radius: { sm: "2px", md: "8px", lg: "12px" },
    colors: {
      brand: "#5e6ad2", "brand-hover": "#828fff", "brand-active": "#7170ff", "brand-foreground": "#ffffff",
      surface: "#191a1b", "surface-raised": "#28282c", "surface-overlay": "#0f1011",
      border: "#333338", primary: "#f7f8f8", secondary: "#d0d6e0", muted: "#62666d",
      error: "#f87171", success: "#4ade80",
      gold: "#FFD700", "gold-light": "#FFED80", silver: "#C0C0C0", bronze: "#CD7F32",
    },
  },
  {
    name: "Spotify",
    fonts: { heading: "Poppins", body: "Poppins", mono: "Geist Mono" },
    typography: { "heading-weight": "700", "heading-tracking": "0", "heading-leading": "1.10", "body-leading": "1.50" },
    radius: { sm: "4px", md: "8px", lg: "16px" },
    colors: {
      brand: "#1ed760", "brand-hover": "#1db954", "brand-active": "#169c46", "brand-foreground": "#181818",
      surface: "#181818", "surface-raised": "#1f1f1f", "surface-overlay": "#252525",
      border: "#4d4d4d", primary: "#ffffff", secondary: "#b3b3b3", muted: "#727272",
      error: "#f3727f", success: "#1ed760",
      gold: "#FFD700", "gold-light": "#FFED80", silver: "#C0C0C0", bronze: "#CD7F32",
    },
  },
  {
    name: "Vercel",
    fonts: { heading: "Inter", body: "Inter", mono: "Geist Mono" },
    typography: { "heading-weight": "600", "heading-tracking": "-0.04em", "heading-leading": "1.00", "body-leading": "1.50" },
    radius: { sm: "4px", md: "8px", lg: "12px" },
    colors: {
      brand: "#171717", "brand-hover": "#333333", "brand-active": "#000000", "brand-foreground": "#ffffff",
      surface: "#ffffff", "surface-raised": "#fafafa", "surface-overlay": "#f5f5f5",
      border: "#e5e5e5", primary: "#171717", secondary: "#4d4d4d", muted: "#808080",
      error: "#ff5b4f", success: "#4ade80",
      gold: "#FFD700", "gold-light": "#b8960b", silver: "#777777", bronze: "#8b5e20",
    },
  },
  {
    name: "Cursor",
    fonts: { heading: "Space Grotesk", body: "Lora", mono: "IBM Plex Mono" },
    typography: { "heading-weight": "400", "heading-tracking": "-0.02em", "heading-leading": "1.10", "body-leading": "1.50" },
    radius: { sm: "2px", md: "8px", lg: "10px" },
    colors: {
      brand: "#f54e00", "brand-hover": "#d94400", "brand-active": "#c03d00", "brand-foreground": "#ffffff",
      surface: "#f2f1ed", "surface-raised": "#eae9e4", "surface-overlay": "#e6e5e0",
      border: "#d5d4cf", primary: "#26251e", secondary: "#6b6a63", muted: "#9a9992",
      error: "#cf2d56", success: "#1f8a65",
      gold: "#c08532", "gold-light": "#a06e20", silver: "#777777", bronze: "#8b5e20",
    },
  },
  {
    name: "Notion",
    fonts: { heading: "Inter", body: "Inter", mono: "IBM Plex Mono" },
    typography: { "heading-weight": "700", "heading-tracking": "-0.03em", "heading-leading": "1.00", "body-leading": "1.50" },
    radius: { sm: "4px", md: "12px", lg: "16px" },
    colors: {
      brand: "#0075de", "brand-hover": "#005bab", "brand-active": "#004a8c", "brand-foreground": "#ffffff",
      surface: "#ffffff", "surface-raised": "#f6f5f4", "surface-overlay": "#ffffff",
      border: "#e0deda", primary: "#191919", secondary: "#615d59", muted: "#a39e98",
      error: "#dd5b00", success: "#2a9d99",
      gold: "#FFD700", "gold-light": "#b8960b", silver: "#777777", bronze: "#8b5e20",
    },
  },
  {
    name: "Raycast",
    fonts: { heading: "Inter", body: "Inter", mono: "Geist Mono" },
    typography: { "heading-weight": "600", "heading-tracking": "0", "heading-leading": "1.10", "body-leading": "1.60" },
    radius: { sm: "6px", md: "12px", lg: "16px" },
    colors: {
      brand: "#FF6363", "brand-hover": "#ff4f4f", "brand-active": "#e55555", "brand-foreground": "#ffffff",
      surface: "#101111", "surface-raised": "#1b1c1e", "surface-overlay": "#222324",
      border: "#2c2d2f", primary: "#ffffff", secondary: "#9c9c9d", muted: "#6a6b6c",
      error: "#FF6363", success: "#5fc992",
      gold: "#ffbc33", "gold-light": "#FFED80", silver: "#C0C0C0", bronze: "#CD7F32",
    },
  },
  {
    name: "Supabase",
    fonts: { heading: "Poppins", body: "Poppins", mono: "Source Code Pro" },
    typography: { "heading-weight": "400", "heading-tracking": "0", "heading-leading": "1.00", "body-leading": "1.50" },
    radius: { sm: "6px", md: "8px", lg: "16px" },
    colors: {
      brand: "#3ecf8e", "brand-hover": "#00c573", "brand-active": "#00a866", "brand-foreground": "#171717",
      surface: "#171717", "surface-raised": "#1c1c1c", "surface-overlay": "#252525",
      border: "#2e2e2e", primary: "#ffffff", secondary: "#b4b4b4", muted: "#898989",
      error: "#e23b4a", success: "#00a87e",
      gold: "#FFD700", "gold-light": "#FFED80", silver: "#C0C0C0", bronze: "#CD7F32",
    },
  },
  {
    name: "Framer",
    fonts: { heading: "DM Sans", body: "Inter", mono: "Azeret Mono" },
    typography: { "heading-weight": "500", "heading-tracking": "-0.04em", "heading-leading": "0.85", "body-leading": "1.30" },
    radius: { sm: "8px", md: "12px", lg: "15px" },
    colors: {
      brand: "#0099ff", "brand-hover": "#007acc", "brand-active": "#0066aa", "brand-foreground": "#ffffff",
      surface: "#000000", "surface-raised": "#090909", "surface-overlay": "#141414",
      border: "#222222", primary: "#ffffff", secondary: "#a6a6a6", muted: "#666666",
      error: "#f87171", success: "#4ade80",
      gold: "#FFD700", "gold-light": "#FFED80", silver: "#C0C0C0", bronze: "#CD7F32",
    },
  },
  {
    name: "Revolut",
    fonts: { heading: "Inter", body: "Inter", mono: "IBM Plex Mono" },
    typography: { "heading-weight": "500", "heading-tracking": "-0.02em", "heading-leading": "1.00", "body-leading": "1.50" },
    radius: { sm: "12px", md: "20px", lg: "20px" },
    colors: {
      brand: "#494fdf", "brand-hover": "#4f55f1", "brand-active": "#3e43c0", "brand-foreground": "#ffffff",
      surface: "#ffffff", "surface-raised": "#f4f4f4", "surface-overlay": "#eeeeee",
      border: "#c9c9cd", primary: "#191919", secondary: "#505a63", muted: "#8d969e",
      error: "#e23b4a", success: "#00a87e",
      gold: "#FFD700", "gold-light": "#b8960b", silver: "#777777", bronze: "#8b5e20",
    },
  },
];
